  name: "Django Mpesa Payment library"
  on:
    push:
      branches:
        - main
      tags:
        - '*'
  jobs:
#    pypi-publish:
#      name: Upload release to PyPI
#      runs-on: ubuntu-latest
#      environment:
#        name: pypi
#        url: https://test.pypi.org/p/dj-mpesa-payment
#      permissions:
#        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
#      steps:
#        - name: Publish package distributions to PyPI
#          uses: pypa/gh-action-pypi-publish@release/v1
#          with:
#            repository-url: https://test.pypi.org/legacy/
    publish:
      runs-on: ubuntu-latest
      environment:
        name: TestPublisher
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install pip and deps
          run: |
            python -m pip install --upgrade pip
            pip install wheel twine
        - name: Install pipenv
          run: |
            python -m pip install pipenv
        - name: Install project dependencies
          run: |
            pipenv install --dev
        - name: Build and publish
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          run: |
            python setup.py sdist bdist_wheel
            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
          # twine upload dist/*