  name: "Django Mpesa Payment library"
  on:
    push:
      tags:
        - '*'
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install pip and deps
          run: |
            python -m pip install --upgrade pip
            pip install wheel twine

        - name: Install pipenv
          run: |
            python -m pip install pipenv

        - name: Install project dependencies
          run: |
            pipenv install --dev

        - name: Build package
#          env:
#            TWINE_USERNAME: __token__
#            TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          run: |
            python setup.py sdist bdist_wheel
#            twine upload dist/*
#            twine upload --repository-url https://test.pypi.org/legacy/ dist/*

    pypi-publish:
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: env
        url: https://pypi.org/p/dj-mpesa-payment
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
        # retrieve your distributions here
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/